remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Art Recognizer
description: An image classification API that classifies 10 different types of arts around the world

author:
  name: Mynul Islam

sass:
  style: :compressed

include:
  - styles.css